In [6]:
import pandas as pd

df1 = pd.read_csv('opendata112N010.csv')
df2=df1.rename(columns={'statistic_yyy':'統計年',
                    'site_id':'區域別',
                    'people_total':'年底人口數',
                    'area':'土地面積',
                    'population_density':'人口密度'})
df3 = df2.drop(index=0)
df3

,統計年,區域別,年底人口數,土地面積,人口密度
1,112,新北市板橋區,554247,23.1373,23955
2,112,新北市三重區,383108,16.3170,23479
3,112,新北市中和區,407273,20.1440,20218
4,112,新北市永和區,214771,5.7138,37588
5,112,新北市新莊區,423607,19.7383,21461
...,...,...,...,...,...
370,112,南沙群島,…,0.5045,…
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN