In [6]:
import pandas as pd

df1 = pd.read_csv('opendata112N010.csv')
df2=df1.rename(columns={'statistic_yyy':'統計年',
                    'site_id':'區域別',
                    'people_total':'年底人口數',
                    'area':'土地面積',
                    'population_density':'人口密度'})
df3 = df2.drop(index=0)
df3

,統計年,區域別,年底人口數,土地面積,人口密度
1,112,新北市板橋區,554247,23.1373,23955
2,112,新北市三重區,383108,16.3170,23479
3,112,新北市中和區,407273,20.1440,20218
4,112,新北市永和區,214771,5.7138,37588
5,112,新北市新莊區,423607,19.7383,21461
...,...,...,...,...,...
370,112,南沙群島,…,0.5045,…
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN

In [7]:
df3.iloc[-10:]

,統計年,區域別,年底人口數,土地面積,人口密度
365,112,連江縣南竿鄉,7827,10.4000,753
366,112,連江縣北竿鄉,3136,9.9000,317
367,112,連江縣莒光鄉,1504,4.7000,320
368,112,連江縣東引鄉,1572,3.8000,414
369,112,東沙群島,…,2.3800,…
370,112,南沙群島,…,0.5045,…
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN

In [9]:
df4 = df3.dropna()
df4

     統計年     區域別   年底人口數     土地面積   人口密度
1    112  新北市板橋區  554247  23.1373  23955
2    112  新北市三重區  383108  16.3170  23479
3    112  新北市中和區  407273  20.1440  20218
4    112  新北市永和區  214771   5.7138  37588
5    112  新北市新莊區  423607  19.7383  21461
..   ...     ...     ...      ...    ...
366  112  連江縣北竿鄉    3136   9.9000    317
367  112  連江縣莒光鄉    1504   4.7000    320
368  112  連江縣東引鄉    1572   3.8000    414
369  112    東沙群島      …    2.3800     …
370  112    南沙群島      …    0.5045     …

[370 rows x 5 columns]

In [10]:
df4.iloc[-10:]

     統計年     區域別  年底人口數     土地面積  人口密度
361  112  金門縣金沙鎮  20858  41.1900   506
362  112  金門縣金寧鄉  35400  29.8540  1186
363  112  金門縣烈嶼鄉  12766  16.0030   798
364  112  金門縣烏坵鄉    664   1.2000   553
365  112  連江縣南竿鄉   7827  10.4000   753
366  112  連江縣北竿鄉   3136   9.9000   317
367  112  連江縣莒光鄉   1504   4.7000   320
368  112  連江縣東引鄉   1572   3.8000   414
369  112    東沙群島     …    2.3800    …
370  112    南沙群島     …    0.5045    …

In [12]:
df5 = df4.drop(columns=['統計年'])
df5

        區域別   年底人口數     土地面積   人口密度
1    新北市板橋區  554247  23.1373  23955
2    新北市三重區  383108  16.3170  23479
3    新北市中和區  407273  20.1440  20218
4    新北市永和區  214771   5.7138  37588
5    新北市新莊區  423607  19.7383  21461
..      ...     ...      ...    ...
366  連江縣北竿鄉    3136   9.9000    317
367  連江縣莒光鄉    1504   4.7000    320
368  連江縣東引鄉    1572   3.8000    414
369    東沙群島      …    2.3800     …
370    南沙群島      …    0.5045     …

[370 rows x 4 columns]

In [14]:
df6 = df5.set_index('區域別')
df6

         年底人口數     土地面積   人口密度
區域別
新北市板橋區  554247  23.1373  23955
新北市三重區  383108  16.3170  23479
新北市中和區  407273  20.1440  20218
新北市永和區  214771   5.7138  37588
新北市新莊區  423607  19.7383  21461
...        ...      ...    ...
連江縣北竿鄉    3136   9.9000    317
連江縣莒光鄉    1504   4.7000    320
連江縣東引鄉    1572   3.8000    414
東沙群島        …    2.3800     …
南沙群島        …    0.5045     …

[370 rows x 3 columns]

In [15]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 新北市板橋區 to 南沙群島
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年底人口數   370 non-null    object
 1   土地面積    370 non-null    object
 2   人口密度    370 non-null    object
dtypes: object(3)
memory usage: 11.6+ KB

In [18]:
df6['土地面積'] = df6['土地面積'].astype(float)

In [ ]:
df6['年底人口數'] = df6['年底人口數'].astype(int)

In [22]:
#不好的處理方式
nums = []
for num in df6['年底人口數']:
    try:
        nums.append(int(num))
    except:
        nums.append(0)
nums

[554247,
 383108,
 407273,
 214771,
 423607,
 304868,
 180658,
 89080,
 115608,
 194399,
 209481,
 37197,
 240828,
 200022,
 92754,
 77491,
 132947,
 23689,
 7166,
 6446,
 22137,
 10752,
 41966,
 4134,
 7915,
 10981,
 20366,
 20869,
 6360,
 193399,
 206759,
 291732,
 216346,
 150155,
 119930,
 173652,
 260313,
 113959,
 276180,
 266951,
 242510,
 470683,
 431255,
 94607,
 180032,
 169237,
 86634,
 178297,
 213403,
 126603,
 229686,
 49277,
 74521,
 13210,
 17784,
 76852,
 126907,
 113548,
 144097,
 235441,
 182232,
 304179,
 163948,
 47468,
 74684,
 89924,
 98805,
 61019,
 53653,
 64362,
 108979,
 95708,
 23089,
 14093,
 31163,
 18073,
 80194,
 55955,
 78413,
 63822,
 198212,
 212511,
 10794,
 74921,
 24251,
 25862,
 20306,
 21616,
 19156,
 43056,
 22420,
 21189,
 20835,
 8728,
 58232,
 24672,
 24990,
 21210,
 18255,
 9994,
 42793,
 52444,
 37624,
 29926,
 7018,
 13043,
 8708,
 7996,
 4231,
 77312,
 68726,
 33270,
 3476,
 234953,
 182034,
 121189,
 126575,
 201824,
 69015,
 78096,
 22539,
 140701,
 197276,
 193139,
 331995,
 49598,
 27098,
 163838,
 179854,
 26220,
 155009,
 356536,
 68216,
 111986,
 40432,
 33729,
 97337,
 44373,
 95574,
 41712,
 28776,
 6530,
 27409,
 50355,
 29525,
 29241,
 13863,
 18273,
 34813,
 34304,
 37008,
 11700,
 5543,
 10955,
 13184,
 1905,
 4230,
 3165,
 94991,
 69960,
 37458,
 28292,
 34948,
 24380,
 32138,
 53249,
 41052,
 21272,
 6036,
 6114,
 215952,
 26825,
 33234,
 96906,
 82617,
 12186,
 58956,
 20377,
 14507,
 8543,
 5192,
 9552,
 4442,
 86307,
 106350,
 43728,
 31300,
 89708,
 34113,
 15212,
 12964,
 31235,
 16505,
 8843,
 9788,
 14949,
 6258,
 11602,
 5975,
 4095,
 5643,
 226046,
 123004,
 84643,
 88046,
 33294,
 53898,
 39336,
 47898,
 16203,
 38491,
 45186,
 38141,
 43936,
 22202,
 40104,
 31048,
 33625,
 35166,
 41415,
 13855,
 25897,
 28946,
 31131,
 14992,
 14297,
 28248,
 97450,
 77035,
 97120,
 51450,
 9924,
 35801,
 16182,
 13528,
 14687,
 16884,
 16085,
 15410,
 15538,
 108172,
 43218,
 70386,
 44494,
 27513,
 37534,
 29846,
 17929,
 27367,
 16635,
 24848,
 22853,
 49533,
 13399,
 11889,
 21739,
 23371,
 21017,
 24985,
 22740,
 39299,
 40705,
 24622,
 29815,
 70248,
 13238,
 30094,
 20889,
 22749,
 16633,
 14123,
 47727,
 42690,
 33308,
 17805,
 10867,
 4444,
 5304,
 193810,
 53325,
 45946,
 29747,
 49252,
 29190,
 10544,
 21639,
 25623,
 23976,
 22764,
 19239,
 52501,
 15807,
 9353,
 22757,
 32674,
 15245,
 16449,
 9882,
 17888,
 12265,
 8029,
 7235,
 5013,
 7742,
 3265,
 6749,
 5291,
 7390,
 4874,
 4777,
 4756,
 103281,
 13078,
 8052,
 16601,
 5553,
 10679,
 7896,
 6649,
 7193,
 7858,
 4373,
 3567,
 4275,
 3439,
 3732,
 5318,
 99043,
 10435,
 22034,
 20307,
 83175,
 16903,
 11739,
 4213,
 10755,
 9627,
 17200,
 6085,
 5973,
 63957,
 16059,
 10087,
 8290,
 5409,
 3937,
 50646,
 52757,
 38450,
 41131,
 45459,
 80440,
 53372,
 223826,
 153759,
 78890,
 117993,
 145591,
 43192,
 31269,
 20858,
 35400,
 12766,
 664,
 7827,
 3136,
 1504,
 1572,
 0,
 0]

In [25]:
def to_int(value):
    try:
        return int(value)
    except:
        return 0

df6['年度人口數'] = df6['年底人口數'].map(to_int)
df6['人口密度'] = df6['人口密度'].map(to_int)

In [28]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 新北市板橋區 to 南沙群島
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年底人口數   370 non-null    object
 1   土地面積    370 non-null    float64
 2   人口密度    370 non-null    int64
 3   年度人口數   370 non-null    int64
dtypes: float64(1), int64(2), object(1)
memory usage: 22.6+ KB

In [29]:
#dataFrame儲存為csv,excel,json

df6.to_csv('人口分佈.csv')

In [31]:
df6.to_excel('人口分佈.xlsx',sheet_name='112年度')